### PR TITLE
Feature/paid user

### PR DESCRIPTION
**Pull request by Lantianyou**

### CODE REVIEW

**Comment by Lantianyou** [comment]
GitHub PR can be quite confusing, watch out haha.
 https://github.com/Yidadaa/ChatGPT-Next-Web/pull/2423#issuecomment-1638009366

**Comment by mengmengmengqiang** [comment]
> GitHub PR can be quite confusing, watch out haha. [Yidadaa#2423 (comment)](https://github.com/Yidadaa/ChatGPT-Next-Web/pull/2423#issuecomment-1638009366)

np problem hh

**Comment by mengmengmengqiang** [comment]
the main branch of repo is master.

**Comment by Lantianyou** [comment]
Thanks, this is in WIP, I will submit a PR about Clerk tomorrow

**Comment by Lantianyou** [comment]
So `master` and `main` will be `developing` and `release` respectively ?

**Pull request merged**
